### PR TITLE
Receive contact requests

### PR DESCRIPTION
**Pull request by pepellou**
@adoankim I just copied some "needs" code to keep a "contacts" collection, so that we can know where someone uses the contact form (either by seeing the data in firebase or via an "evil" console.log I added).

The thing is I receive a PERMISSION_DENIED error when trying to push the data to the new collection. Since the firebase collection is in your account, can you verify it or continue my work from this point? :-)

### CODE REVIEW

**Comment by adoankim** [comment]
@pepellou ok, the problem was on db permission rules. I just allowed RW on that collection, it should working now.

Maybe we could setup a new Firebase project with meanit account, so that everybody in the team will have the access 😄

**Comment by pepellou** [comment]
@adoankim ok, I think that's a good idea, I'll do it today and include the new credentials setup in this PR.

**Comment by pepellou** [comment]
I've just deployed what we had to gh-pages, and it's working. This way we can see if anyone contacts us, although I expect to be able to replace it with the new Firebase account tonight ;-)

**Comment by pepellou** [comment]
@adoankim I created the Firebase project with the meanit account and updated the credentials in the config. So this PR can be reviewed/approved/merged if you want.

(gh-pages is already rebased with this branch)

**Comment by pepellou** [comment]
Fixes #7

**Pull request merged**
